config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trips
  resources :days, only: [:index, :create, :update, :destroy, :show]
  resources :destinations, only: [:index]

  post '/trips/:id/invite', to: 'trips#invite_friends'
  get '/trips/:id/destinations', to: 'trips#destinations'
  get 'pages/index'
  root to: 'pages#index'
  get '/dashboard', to: 'pages#dashboard'

  post '/trips/:id/invite', to: 'trips#invite_friends'
  get '/trips/:id/destinations', to: 'trips#destinations'
  put '/trips/:id', to: 'trips#update'
  delete  '/trips/:id', to: 'trips#destroy'

  post '/api/destinations', to:'destinations#create'
  delete 'destinations', to: 'destinations#destroy_all'

  delete '/api/destinations', to: 'destinations#destroy'
  put 'api/destinations/edit', to: 'destinations#update'

  

end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id         :integer          not null, primary key
#  location   :string
#  name       :string
#  start_date :date
#  end_date   :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Trip < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :destinations
  has_many :days

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    def index
        @trips = Trip.all
    end

    def show
        @trip = Trip.find(params[:id])
        render json: @trip
    end

    def new
        @trip = Trip.new
    end

    def edit
        @trip = Trip.find(params[:id])
    end

    def create
        @trip = Trip.new(trip_params)
        @trip.users << current_user

        if @trip.save
            p "saved"
            create_days
            render :json => @trip
        else
            redirect_to root
            p "error making trip. see controller to debug"
        end
    end

    def update
        @trip = Trip.find(params[:id])

        if @trip.update(trip_params)
            # redirect_to @trip
            #json1 = {:status => 1, :trip => @trip}
            @trip.days.destroy_all
            create_days
	        render :json => @trip
        else
            # render 'edit'
            json1 = {:status => -1, :errors => @trip.errors}
	        #render :json => json1
        end
    end

    def destroy
        @trip = Trip.find(params[:id])
        @trip.destroy

        respond_to do |format|
          format.html { redirect_to current_page_url, notice: 'page was successfully destroyed.' }
          format.json { head :no_content }
        end
    end

    def invite_friends
        if !params[:id]
          render :json => {:status => -1, :errors => "Required field 'trip_id' missing"}
          return
        end
        @trip = Trip.find(params[:id])
        @emails = params[:emails]

        @emails.each do |email|
            p email
            invitee = User.find_by(email: email)
            if (invitee) && (not @trip.users.include?(invitee))
                @trip.users << invitee
            elsif not invitee
                p "no such invitee exists"
                p current_user.name
                PageMailer.invite_email(current_user, email).deliver_now
            end
        end
        render json: @trip
    end

    def destinations
        if !params[:id]
          render :json => {:status => -1, :errors => "Required field 'trip_id' missing"}
          return
        end

        @trip = Trip.find(params[:id])
        @destinations = @trip.destinations

        if @destinations.blank?
          render :json => {:status => -1, :errors => "Invalid trip id"}
          return
        end

        render :json => { destinations: @destinations}
    end

    private
        def trip_params
            params.require(:trip).permit(:name, :location, :start_date, :end_date)
        end

        def create_days
            days = (@trip.start_date..@trip.end_date).map(&:to_s)
            days.each do |day|
                @trip.days.create({date: day})
            end
        end
end

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
 
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@trip.errors.count, "error") %> prohibited
        this trip from being saved:
      </h2>
      <ul>
        <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
  
    <p>
        <%= f.label :start %><br>
        <%= f.text_field :start %>
      </p>
  
    <p>
    <%= f.label :end %><br>
    <%= f.text_field :end %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>
 
<%= link_to 'Back', trips_path %>

app/views/trips/edit.html.erb
<h1>Edit Trip</h1>
 
<%= render 'form' %>

app/views/trips/index.html.erb
<h1>Listing Trips</h1>

<%= link_to 'New Trip', new_trip_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Created</th>
    <th>Updated</th>
    <th>User ID</th>
    <th colspan="3"></th>
  </tr>
 
  <% @trips.each do |trip| %>
    <tr>
      <td><%= trip.id %></td>
      <td><%= trip.name %></td>
      <td><%= trip.location %></td>
      <td><%= trip.start %></td>
      <td><%= trip.end %></td>
      <td><%= trip.created_at.in_time_zone("Pacific Time (US & Canada)") %></td>
      <td><%= trip.updated_at.in_time_zone("Pacific Time (US & Canada)") %></td>
      <td><%= trip.user_id %></td>
      <td><%= link_to 'Show', trip_path(trip) %></td>
      <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
      <td><%= link_to 'Destroy', trip_path(trip),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/trips/new.html.erb
<h1>New Trip</h1>
 
<%= render 'form' %>

app/views/trips/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @trip.name %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @trip.location %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @trip.start %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @trip.end %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>